### ISSUE TITLE
Examples (projects) are not working

### ISSUE THREAD

**Issue by pjdewitte** [wvisser1958/GSPy#4]
Currently, the examples are not working.

Stack trace for `projects/turbojet/turbojet.py`:

> Traceback (most recent call last):
>   File "C:\Users\dewitte\Documents\Synced\0 - General\Code\GSPy\src\gspy\core\system.py", line 118, in Run_DP_simulation
>     Do_Run(0, states)    # in DP always fsys.states = [1, 1, 1, 1, .....]
>     ~~~~~~^^^^^^^^^^^
>   File "C:\Users\dewitte\Documents\Synced\0 - General\Code\GSPy\src\gspy\core\system.py", line 105, in Do_Run
>     comp.Run(Mode, PointTime)
>     ~~~~~~~~^^^^^^^^^^^^^^^^^
>   File "C:\Users\dewitte\Documents\Synced\0 - General\Code\GSPy\src\gspy\core\turbine.py", line 141, in Run
>     solution = root(pressure_ratio_for_turbine_power, initial_guess)
>   File "C:\Users\dewitte\Documents\Synced\0 - General\Code\GSPy\.venv\Lib\site-packages\scipy\optimize\_root.py", line 254, in root
>     sol = _root_hybr(_wrapped_fun, x0, args=args, jac=jac, **options)
>   File "C:\Users\dewitte\Documents\Synced\0 - General\Code\GSPy\.venv\Lib\site-packages\scipy\optimize\_minpack_py.py", line 239, in _root_hybr
>     shape, dtype = _check_func('fsolve', 'func', func, x0, args, n, (n,))
>                    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\dewitte\Documents\Synced\0 - General\Code\GSPy\.venv\Lib\site-packages\scipy\optimize\_minpack_py.py", line 24, in _check_func
>     res = atleast_1d(thefunc(*((x0[:numinputs],) + args)))
>                      ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\dewitte\Documents\Synced\0 - General\Code\GSPy\.venv\Lib\site-packages\scipy\optimize\_root.py", line 216, in _wrapped_fun
>     return fun(*fargs)
>   File "C:\Users\dewitte\Documents\Synced\0 - General\Code\GSPy\src\gspy\core\turbine.py", line 118, in pressure_ratio_for_turbine_power
>     PW_PR = fu.TurbineExpansion(self.GasIn, self.GasOut, PR_iter, self.Eta, None, self.Polytropic_Eta)
>   File "C:\Users\dewitte\Documents\Synced\0 - General\Code\GSPy\src\gspy\core\utils.py", line 156, in TurbineExpansion
>     GasOut.SP = GasIn.entropy_mass, Pout
>     ^^^^^^^^^
>   File "C:\Users\dewitte\Documents\Synced\0 - General\Code\GSPy\.venv\Lib\site-packages\cantera\composite.py", line 376, in setter
>     setattr(self.phase, attr, value)
>     ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "cantera/thermo.pyx", line 1542, in cantera.thermo.ThermoPhase.SP.__set__
> TypeError: only 0-dimensional arrays can be converted to Python scalars
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\dewitte\Documents\Synced\0 - General\Code\GSPy\projects\turbojet\turbojet.py", line 161, in <module>
>     main()
>     ~~~~^^
>   File "C:\Users\dewitte\Documents\Synced\0 - General\Code\GSPy\projects\turbojet\turbojet.py", line 121, in main
>     fsys.Run_DP_simulation()
>     ~~~~~~~~~~~~~~~~~~~~~~^^
>   File "C:\Users\dewitte\Documents\Synced\0 - General\Code\GSPy\src\gspy\core\system.py", line 121, in Run_DP_simulation
>     Do_Output(0, ExceptionError)
>     ~~~~~~~~~^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\dewitte\Documents\Synced\0 - General\Code\GSPy\src\gspy\core\system.py", line 200, in Do_Output
>     comp.PrintPerformance(Mode, PointTime)
>     ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
>   File "C:\Users\dewitte\Documents\Synced\0 - General\Code\GSPy\src\gspy\core\gaspath.py", line 60, in PrintPerformance
>     print(f"\t\tMass flow  : {self.W:.2f} kg/s")
>                               ^^^^^^
> AttributeError: 'TDuct' object has no attribute 'W'. Did you mean: 'Wc'?

Notice there are two errors:

>   File "C:\Users\dewitte\Documents\Synced\0 - General\Code\GSPy\src\gspy\core\utils.py", line 156, in TurbineExpansion
>     GasOut.SP = GasIn.entropy_mass, Pout
>     ^^^^^^^^^
>   File "C:\Users\dewitte\Documents\Synced\0 - General\Code\GSPy\.venv\Lib\site-packages\cantera\composite.py", line 376, in setter
>     setattr(self.phase, attr, value)
>     ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "cantera/thermo.pyx", line 1542, in cantera.thermo.ThermoPhase.SP.__set__
> TypeError: only 0-dimensional arrays can be converted to Python scalars

and

>   File "C:\Users\dewitte\Documents\Synced\0 - General\Code\GSPy\src\gspy\core\gaspath.py", line 60, in PrintPerformance
>     print(f"\t\tMass flow  : {self.W:.2f} kg/s")
>                               ^^^^^^
> AttributeError: 'TDuct' object has no attribute 'W'. Did you mean: 'Wc'?

The examples seem to be broken since commit ab05740 ("version 1.2, see readme.md for details").
